services:
  minecraft:
    build:
      context: .
      args:
        PAPER_VERSION: "1.21.11"
        PAPER_BUILD: "69"
        MC_RAM: "2G"
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - world-data:/server/world
      - plugins:/server/plugins
      - logs:/server/logs
    environment:
      - MC_RAM=2G
      - RCON_PASSWORD=changeme
    restart: unless-stopped

volumes:
  world-data:
  plugins:
  logs:
